---
name: Feature Request Template
about: "For feature requests. Please search for existing issues first."
labels: enhancement 
---

### Feature request

<!-- Describe the feature request -->

### Current behaviour

<!-- What's currently happening? -->

### Screenshots (if applicable)

<!-- Include screenshots if applicable. -->